fixtures:
  repositories:
    "inifile": "https://github.com/puppetlabs/puppetlabs-inifile.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "satellite_pe_tools": "#{source_dir}"
